### ISSUE TITLE
Why Deprecation

### ISSUE THREAD

**Issue by JProof** [joomla-framework/image#21]
Hi,
just a short question, why is it deprecated?

**Comment by zero-24** [comment]
Hmm on a quick look it seems that we no longer use that package in 4.x: https://github.com/joomla/joomla-cms/blob/4.0-dev/composer.json#L34

Maybe @wilsonge or @HLeithner know details here?

**Comment by JProof** [comment]
Okay, thank you

looks like is "hard-coded" https://github.com/joomla/joomla-cms/tree/4.1-dev/libraries/src/Image

**Comment by zero-24** [comment]
As said i dont know why that package here is deprecated nor why we dont use the package in 4.x we might wait for the two mention people to take a look before this issue is closed?

**Comment by JProof** [comment]
;-) jupp

**Comment by xillibit** [comment]
The deprecation message has never been updated  : https://github.com/joomla/joomla-cms/issues/29853#issuecomment-651745026

**Comment by mbabker** [comment]
Because there are more feature complete and better maintained image manipulation libraries in the PHP ecosystem than anything Joomla could ever produce.  The `Joomla\CMS\Image` API is more than enough for the small handful of developers in Joomla who might actually perform image manipulation in the context of the CMS environment, but as a standalone tool this package will never live up to something like https://github.com/avalanche123/Imagine and deprecating it is in everyone’s best interests.  And, if being honest, at the time the decision was made well over 95% of maintenance time on this GitHub organization came from me and me alone, and I have better things to do than reinvent wrappers around the GD library.

**Comment by JProof** [comment]
thank you mbabker
